export const primaryColor = "#391DDD"
export const secondaryColor = "#FF909E"
export const darkerPrimaryColor = "#2f17b5"
export const darkerSecondaryColor = "#FF7C8C"

export const blackColor = "#212529"
export const darkBlueColor = "#0C14B1"
export const darkGreyColor = "4D4771"
export const greyColor = "#E1E4E8"
export const lightGreyColor = "#DDDDDD"
export const pinkColor = "#FF5477"
export const redColor = "#E52312"
export const superLightRedColor = "#FFE7E7"
export const lightYellowColor = "#FFF7C3"
export const darkWarnColor = "#D9B600"
export const warnColor = "#FFF6BB"
export const whiteColor = "#FFFFFF"