export default {
  Buttons: 'Buttons',
  Cards: 'Cards',
  Checkbox: 'Checkbox',
  Containers: 'Containers',
  Dropdowns: 'Dropdowns',
  Footers: 'Footers',
  Headers: 'Headers',
  Icons: 'Icons',
  Images: 'Images',
  Inputs: 'Inputs',
  Logos: 'Logos',
  Modals: 'Modals',
  Radios: 'Radios',
  StickyToasts:'StickyToasts',
  Snackbar: 'Snackbar',
  Selects: 'Selects',
  Spinners:'Spinners',
  Tabs:'Tabs',
  Toasts: 'Toasts',
  Typographys: 'Typographys'
}